#!/usr/bin/env bash

EXEC_DIR=`dirname $0`

if [ "$1" = "" ]; then
    echo "ERROR: The 'daemon' script requires a version as a passed positional parameter."
    exit 127
fi

cd $EXEC_DIR
source versions

VERSION=$1 \
    MESOS_VERSION=${MESOS_VERSIONS[$VERSION]} \
    MESOMATIC_VERSION=${MESOMATIC_VERSIONS[$VERSION]} \
    make daemon-start;
