FROM mesosphere/mesos:$MESOS_VERSION
MAINTAINER Clojure-Aided Enrichment Center <https://github.com/clojusc>

ENV MESOS_WORK_DIR /root
EXPOSE 5050

CMD ["mesos", "local", "--ip=0.0.0.0", "--log_dir=/tmp/mesos"]

