FROM mesosphere/mesos:$MESOS_VERSION
MAINTAINER Clojure-Aided Enrichment Center <https://github.com/clojusc>

ENV DEBIAN_FRONTEND noninteractive
ENV LEIN_JVM_OPTS -Dhttps.protocols=TLSv1.2
ENV MESOS_NATIVE_JAVA_LIBRARY /usr/lib/libmesos.so
ENV MESOS_WORK_DIR /root
EXPOSE 5050

RUN \
    ### Setup required packages
    apt-get update -y && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* && \
    ### Install lein
    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && \
    chmod 755 lein && \
    mv lein /usr/local/bin && \
    ### Install mesomatic
    git clone https://github.com/clojusc/mesomatic.git && \
    cd mesomatic && \
    git checkout $MESOMATIC_VERSION && \
    lein test && \
    lein install && \
    ### Install mesomatic-testing
    git clone https://github.com/clojusc/mesomatic-testing.git && \
    cd mesomatic-testing && \
    git checkout $MESOMATIC_TESTING_VERSION && \
    lein test && \
    lein install

CMD ["mesos", "local", "--ip=0.0.0.0", "--log_dir=/tmp/mesos"]
