#!/usr/bin/env bash

EXEC_DIR=`dirname $0`

cd $EXEC_DIR
source versions

VERSION="1.0.1" \
    MESOS_VERSION=${MESOS_VERSIONS[$VERSION]} \
    MESOMATIC_VERSION=${MESOMATIC_VERSIONS[$VERSION]} \
    make push;
